version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mychatapp
      POSTGRES_PASSWORD: "YM1voVw64KXkPdR6PBHd0dVg_QrKg7MS"
    volumes:
      - mychatapp_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "QhflLOEYDJaAnVWKIaMCl6Ih-ib0aD4R"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  mychatapp_data:
